runtime: nodejs20

# handlers:
#   # Serve static files from the build folder
#   - url: /static
#     static_dir: build/static

#   # Serve the main HTML file
#   - url: /.*
#     static_files: build/index.html
#     upload: build/index.html
